### ISSUE TITLE
Add Raspberry Pi 4 support

### ISSUE THREAD

**Issue by Tiryoh** [rt-net/RaspberryPiMouse#21]
## TODO

- [x] Raspberry Pi 4対応のドライバを用意
  - #22 にて対応予定
- [x] Raspberry Pi 4Bを搭載したRaspberry Pi Mouse V3にて動作確認
- [x] Raspberry Pi 3B/3B+を搭載したRaspberry Pi Mouse V3にて動作確認
- [x] ビルド方法についてドキュメント作成

## 資料

* Raspberry Pi 4でレジスタにアクセスしているコード
  * https://github.com/RPi-Distro/raspi-gpio/commit/80fa7d04eafb3ea34fc6f2d32de5f1873b5fb369#diff-43a345de26e51e739c07a172dd183d89
* BCM2711の資料まとめ
  * https://qiita.com/eggman/items/402d8ba20fa021cc4531

**Comment by Tiryoh** [comment]
#22 #43 にて対応したのでクローズします。

**Comment by Tiryoh** [comment]
#62 にて[`./utils/build_install.bash`](https://github.com/rt-net/RaspberryPiMouse/blob/master/utils/build_install.bash)を実行すればRaspberry Pi 4向けのデバイスドライバがビルドされ、インストールできるようになりました。
